### ISSUE TITLE
ADD SUPORTS PLUGINS 

### ISSUE THREAD

**Issue by davee261** [xJon/Tekkit-2#107]
Hello, would it be possible to add plugin support please? or is there any instruction how to add them there yourself? Thank you.

**Comment by Lumpous** [comment]
Plugins are meant to run on servers.
I'm not quite sure how Tekkit 2 is meant to be played, whether it's more SP or MP balanced.

But I'm sure the type of plugin support should be up to each server owner, since the plugins supported depend on the plugin support.

Defaulting a specific plugin support would not be helpful here, as the owner would have chosen a completely different one and would have to change it himself in this case.
Which in turn could lead to unexpected problems if the server package were optimized for a different one.

So my bold suggestion is to leave the decision and selection of plugin support solely to the respective server operator.

**Comment by UeberallGebannt** [comment]
If you're talking about Bukkit/Spigot plugin support, there are multiple options.
I'm using [Magma](https://magmafoundation.org) for my server.

You will face some issues though and I doubt you will get support here on the official modpack bugtracker.

**Comment by RadegasTCZ** [comment]
I have sticked to SpongeForge solution with 2 mods, essentials and tablist.

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
