### ISSUE TITLE
Logistics Pipes issue with IC2 Classic Reactor

### ISSUE THREAD

**Issue by xiaoxinny** [xJon/Tekkit-2#225]
**Basic details**
- **Are you using a legitimate Minecraft account?**: Yes
- **Are you using Java 8, 64-bit?**: Yes
- **Did you add any additional mods**: No, except Sphax as a resource pack.
- **Crash/latest log link (if applicable)**: Attached below.

**Describe the issue**
Initially, I had thought that the cooling parts in the nuclear reactors melted, so I replaced them consistently. (a bit of cheats were used here)
But every time that occurs, after the parts were placed in (in an automatic passive cooling setup), the nuclear reactor would for some reason clear itself out, and when this occurs during the running of the reactor, the whole room blows up.
I made a 16 nuclear reactor set-up, with 28 Electric Overclocked Heating Vents and 15 Component Heat Exchangers, and 11 Dual Netherstar Enriched Uranium Cells, and connected each of them to a thermal monitor set at 500. red alloy wire attached, and each nuclear reactor has a MK4 Logistics Chassis attached which contains an Advanced Extractor Module to remove near-depleted cells, and an ItemSink module to fill the empty spaces with dual uranium cells, all in all connected to a crystal chest with a MK4 Logistics Chassis containing 2 QuickSort, 1 Active Supplier Module requesting for dual uranium cells, and 1 ItemSink requesting for near-depleted cells.
This has blown up my word 3 times as of now, and I've had to constantly restore from backup. The logs appear to indicate that there is an issue with the logs chassis connected to my crystal chest. I have ruled out the nuclear reactors being the issue as initially I had thought the first nuclear reactor being the issue and always clearing out, but after disconnecting it from the logs pipe network, the second one in the row was cleared out instead.

[crash-2023-09-19_13.37.42-server.txt](https://github.com/xJon/Tekkit-2/files/12658479/crash-2023-09-19_13.37.42-server.txt)
[2023-09-19-4.log](https://github.com/xJon/Tekkit-2/files/12658480/2023-09-19-4.log)
https://mclo.gs/tM5nMoI
https://mclo.gs/8kozRXE
![image](https://github.com/xJon/Tekkit-2/assets/106980227/7ccbe8eb-f5e0-4b39-a803-2e36340055e9)

**Comment by xJon** [comment]
Indeed I see an issue in the log between Logistics Pipes and IC2 Classic. You've also included another crash report, how is that related to the reported issue?

**Comment by Dylankjy** [comment]
I'm going to add on to @xiaoxinny's bug report. For context, I play on LAN with him and set up the logistics network for the reactors.

The reactors are connected to a single chest meant to supply the reactors with uranium cells with a QuickSort module.
Each Reactor has a Mk 2 Logistic Chassis connected with an Advanced Extractor Module (Depleted Uranium) and an ItemSink (Uranium Cell).

It should be noted that when the QuickSort module is added into the chest's chassis, the uranium cell is then transported to the Reactor. The moment this happens, the reactor losses all its items in its inventory and because there is no heat vent items in it, it causes an explosion.

So the main gist of the bug is: the QuickSort module is clearing the inventory of the Reactor which is should not do.

**Comment by xJon** [comment]
This should be resolved now in `1.2.3`.
