### ISSUE TITLE
Logistical Pipes not sending Lava cells to geothermal generators

### ISSUE THREAD

**Issue by SparksSkywere** [xJon/Tekkit-2#86]
**Basic details**
- **Are you using a legitimate Minecraft account?**: yes
- **Are you using Java 8, 64-bit?**: yes
- **Did you add any additional mods**: no
- **Crash/latest log link (if applicable)**: not applicable

**Describe the issue**

Recently some Geothermal generators plugged into a logistic network do not accept lava cells post update, the previous update it worked fine, Thermal generators do accept lava cells on the logistic network.

Configuration of how it works:

Condenser with lava cell generation -> Provider Pipe out -> Supplier pipe into geothermal generator set with lava cell and request mode infinite, when a 32 stack is sent in the logistic network will send all the required supplies to the generator overtime it will keep stock of a full stack.

**Comment by SparksSkywere** [comment]
I have pictures of the issue from a player and my own generator farm (I use thermal only), I can do a PM if you wish to see them or I can throw them all into here?

**Comment by SparksSkywere** [comment]
And extra note, the geothermal generators do not accept any input, even from Hoppers.

**Comment by xJon** [comment]
You need to make sure you have an automation upgrade.

**Comment by SparksSkywere** [comment]
> You need to make sure you have an automation upgrade.

I had a reply from one the players who has been helping me test things while I am at work:

"also ya just tested, geothermal and thermal generators dont take automation upgrades at all, so dunno what he is on about
and now on earth, Zielo's thermals wont accept. and there is no upgrading slots at all
https://forum.industrial-craft.net/thread/2449-minor-bug-1-23-geothermal-generator-can-only-accept-lava-from-the-bottom-slot/ this is whats happening"

**Comment by Lumpous** [comment]
https://user-images.githubusercontent.com/112988030/190380447-b16f7590-e92a-4fba-974e-f2f0497bfe54.mp4

Inserting Automation Upgrades into geothermals works just fine to me.

**Comment by xJon** [comment]
Seems that you need to use a [Machine Tool](https://github.com/TinyModularThings/IC2Classic/wiki/Machine-Tool).

**Comment by TechnoRikkor** [comment]
at the time, didnt know about the machine tool or even its usage tbh. i havent at the moment tried using a machine tool. i havent lately done more testing using the machine tool and automation upgrade so cant at the moment expand further (im about to head to work) but i have at least found thermal generators (without automation upgrade) will accept input from the bottom of them and geothermals wont. (again this is without automation upgrades). when i get home from work since ive got a ton of extra geothermals still, ill test the various things and see if there is an existing issue or not

**Comment by xJon** [comment]
Closing for now (will reopen if requested).
